engines:
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
  markdownlint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
ratings:
  paths:
  - "src/**"
exclude_paths:
- "docs/"
- "logs/"
- "src/static/"
- "src/**/migrations/"
