language: python
python:
  - "3.5"
env:
  - DJANGO_VERSION=1.10
install:
  - pip install -r requirements.txt
  - cd ..
  - cd src
  - python manage.py migrate
script:
  - python manage.py test profiles
