language: python
python:
  - "3.5.2"
env:
  - DJANGO_VERSION=1.10.6
install:
  - pip install -r requirements.txt
  - pwd
  - cd src
  - cp storemanager/settings/local.sample.env storemanager/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test profiles
