version: '2'
services:

  db:
    container_name: db
    image: postgres
    ports:
        - "5432:5432"
    volumes:
      - dsm_dblib:/var/lib/postgresql
      - dsm_dbrun:/run/postgresql

  web:
    container_name: web
    build: ./web
    command: python manage.py runserver_plus 0.0.0.0:8015
    # restart: always
    volumes:
      - ./web/code:/code
      - ./docs:/docs
      # - ./site-packages:/usr/local/lib/python3.5/site-packages
    ports:
      - "8015:8015"
    depends_on:
      - db

volumes:
  dsm_dblib:
  dsm_dbrun:

networks:
  default:
    external:
      name: dtgnet
