version: '2'
services:

  db:
    build: ./db
    volumes:
      - ./db/dblib:/var/lib/postgresql
      - ./db/dbrun:/run/postgresql

  web:
    build: ./web
    command: python manage.py runserver_plus 0.0.0.0:8015
    # restart: always
    volumes:
      - ./web/code:/code
      # - /usr/local/lib/python3.5/site-packages
    ports:
      - "8015:8015"
    depends_on:
      - db
